[build]
rustflags = [
    "-C", "target-cpu=native",
    "-Dwarnings",
]

[alias]
clippy-strict = [
    "clippy", "--",
    "-W", "clippy::all",
    "-W", "clippy::pedantic",
    "-W", "clippy::nursery",
    "-W", "clippy::cargo",
    "-W", "clippy::perf",
    "-W", "clippy::complexity",
    "-W", "clippy::style",
    "-D", "clippy::correctness",
    "-D", "clippy::suspicious",
    "-A", "clippy::module_name_repetitions",
    "-A", "clippy::must_use_candidate",
]
